TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 0.75
  min_in_place_vel_theta: 0.2

  acc_lim_theta: 1.6 # 3.2
  acc_lim_x: 1.0 # 2.5
  acc_lim_y: 1.0 # 2.5


  holonomic_robot: true