local_costmap:
  global_frame: map #changed to odom from map, this must be tested!
  robot_base_frame: base_link  
  update_frequency: 5.0
  publish_frequency: 5.0
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05